set_property IOSTANDARD LVCMOS33 [get_ports {data_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rx_done_o]
set_property IOSTANDARD LVCMOS33 [get_ports rx_i]
set_property PACKAGE_PIN K17 [get_ports clk]
set_property PACKAGE_PIN G15 [get_ports rst_n]
set_property PACKAGE_PIN R14 [get_ports rx_i]

set_property PACKAGE_PIN T12 [get_ports {data_o[7]}]
set_property PACKAGE_PIN Y14 [get_ports {data_o[6]}]
set_property PACKAGE_PIN W14 [get_ports {data_o[5]}]
set_property PACKAGE_PIN T10 [get_ports {data_o[4]}]
set_property PACKAGE_PIN M14 [get_ports {data_o[3]}]
set_property PACKAGE_PIN M15 [get_ports {data_o[2]}]
set_property PACKAGE_PIN G14 [get_ports {data_o[1]}]
set_property PACKAGE_PIN D18 [get_ports {data_o[0]}]

set_property PACKAGE_PIN V15 [get_ports rx_done_o]
