webtalk_init -webtalk_dir C:/Users/vamsi/Desktop/MiniProject_Assignments/FPGA/UART_RX/UART_RX.sim/sim_1/behav/xsim/xsim.dir/tb_uart_rx_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 28 01:29:21 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "82165769-bbc2-426f-b482-85ddc4c34838" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2fec0c95ecd746b6be11b123664d021a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1805 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2640 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6484_KB" -context "xsim\\usage"
webtalk_transmit -clientid 823405714 -regid "" -xml C:/Users/vamsi/Desktop/MiniProject_Assignments/FPGA/UART_RX/UART_RX.sim/sim_1/behav/xsim/xsim.dir/tb_uart_rx_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/vamsi/Desktop/MiniProject_Assignments/FPGA/UART_RX/UART_RX.sim/sim_1/behav/xsim/xsim.dir/tb_uart_rx_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/vamsi/Desktop/MiniProject_Assignments/FPGA/UART_RX/UART_RX.sim/sim_1/behav/xsim/xsim.dir/tb_uart_rx_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
